from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

MAX_PROMPT_CHARS = 20_000
PRIMARY_SOURCE_LINE_LIMIT = 15

# -------------------------------------------------------------------
# Jinja2 setup
# -------------------------------------------------------------------

PROMPTS_DIR = Path(__file__).parent.parent / "prompts"

jinja_env = Environment(
    loader=FileSystemLoader(PROMPTS_DIR),
    trim_blocks=True,
    lstrip_blocks=True,
    autoescape=select_autoescape(enabled_extensions=()),
)

PROMPT_TEMPLATE = jinja_env.get_template("explain_node.j2")

# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------

def _truncate_to_lines(text: str, max_lines: int) -> str:
    if not text:
        return ""

    return "\n".join(text.splitlines()[:max_lines])


def _normalize_comments(node: dict) -> list[str]:
    """
    Expected format inside node.attributes:

    {
        "comments": [
            "...",
            "..."
        ]
    }
    """

    attributes = node.get("attributes") or {}
    comments = attributes.get("comments") or []

    cleaned: list[str] = []

    for comment in comments:
        if not isinstance(comment, str):
            continue

        stripped = comment.strip()

        if not stripped:
            continue

        # Skip noisy/generated comments
        lowered = stripped.lower()

        if (
            lowered.startswith("copyright")
            or lowered.startswith("license")
            or lowered.startswith("generated by")
        ):
            continue

        cleaned.append(stripped)

    return cleaned


def _prepare_node(
    node: dict,
    *,
    truncate_source: bool = False,
) -> dict:

    raw_source = (node.get("raw_source") or "").rstrip()

    if truncate_source:
        raw_source = _truncate_to_lines(
            raw_source,
            PRIMARY_SOURCE_LINE_LIMIT,
        )

    return {
        "id": node.get("id"),
        "name": node.get("name"),
        "qualified_name": node.get("qualified_name") or "N/A",
        "type": node.get("type") or "N/A",
        "path": node.get("path") or "N/A",
        "language": node.get("language") or "N/A",
        "summary": node.get("summary") or "N/A",
        "comments": _normalize_comments(node),
        "raw_source": raw_source,
    }


def _prepare_relationships(
    edges: list[dict],
    node_index: dict[str, dict],
) -> list[str]:

    relationships: list[str] = []

    for edge in edges:
        source_node = node_index.get(edge.get("source_id", ""))

        if not source_node:
            continue

        if source_node.get("type") == "module":
            continue

        target_id = edge.get("target_id")
        target_node = (
            node_index.get(target_id)
            if target_id
            else None
        )

        if target_node and target_node.get("type") == "module":
            continue

        source_name = (
            source_node.get("qualified_name")
            or edge.get("source_id")
            or "N/A"
        )

        edge_type = edge.get("type") or "N/A"

        target_ref = (
            edge.get("target_ref")
            or target_id
            or "N/A"
        )

        relationships.append(
            f"{source_name} --[{edge_type}]--> {target_ref}"
        )

    return relationships


def _render_prompt(
    *,
    query: str,
    seed_nodes: list[dict],
    related_nodes: list[dict],
    relationships: list[str],
) -> str:

    return PROMPT_TEMPLATE.render(
        query=query,
        seed_nodes=seed_nodes,
        related_nodes=related_nodes,
        relationships=relationships,
    )


# -------------------------------------------------------------------
# Public API
# -------------------------------------------------------------------

def build_explanation_prompt(
    query: str,
    seed_nodes: list[dict],
    related_nodes: list[dict],
    edges: list[dict],
    node_index: dict[str, dict],
) -> str:

    filtered_seed_nodes = [
        node
        for node in seed_nodes
        if node.get("type") != "module"
    ]

    filtered_related_nodes = [
        node
        for node in related_nodes
        if node.get("type") != "module"
    ]

    relationships = _prepare_relationships(
        edges,
        node_index,
    )

    # ---------------------------------------------------------------
    # Full prompt
    # ---------------------------------------------------------------

    prepared_seed_nodes = [
        _prepare_node(node)
        for node in filtered_seed_nodes
    ]

    prepared_related_nodes = [
        _prepare_node(node)
        for node in filtered_related_nodes
    ]

    prompt = _render_prompt(
        query=query,
        seed_nodes=prepared_seed_nodes,
        related_nodes=prepared_related_nodes,
        relationships=relationships,
    )

    if len(prompt) <= MAX_PROMPT_CHARS:
        return prompt

    # ---------------------------------------------------------------
    # Remove related source code first
    # ---------------------------------------------------------------

    prepared_related_nodes = [
        {
            **_prepare_node(node),
            "raw_source": "",
        }
        for node in filtered_related_nodes
    ]

    prompt = _render_prompt(
        query=query,
        seed_nodes=prepared_seed_nodes,
        related_nodes=prepared_related_nodes,
        relationships=relationships,
    )

    if len(prompt) <= MAX_PROMPT_CHARS:
        return prompt

    # ---------------------------------------------------------------
    # Truncate primary source last
    # ---------------------------------------------------------------

    truncated_seed_nodes = [
        _prepare_node(
            node,
            truncate_source=True,
        )
        for node in filtered_seed_nodes
    ]

    return _render_prompt(
        query=query,
        seed_nodes=truncated_seed_nodes,
        related_nodes=prepared_related_nodes,
        relationships=relationships,
    )