services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      db:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - ./temp/test_project:/repos/target

  db:
    image: pgvector/pgvector:pg17
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql

  ollama:
    image: alpine/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    mem_limit: 2g
    environment:
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_KEEP_ALIVE=5m
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10

  ollama-init:
    image: alpine/ollama
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: sh -c "OLLAMA_HOST=http://ollama:11434 ollama pull unclemusclez/jina-embeddings-v2-base-code:q4"
    restart: "no"

volumes:
  pgdata:
  ollama_data: